version: '3.8'

services:
  frontend:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
    ports:
      - '3030:3000'
